net-il-mio-fotoalbum/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using net_il_mio_fotoalbum.Models;

namespace net_il_mio_fotoalbum.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {

        private readonly ILogger<CategoryController> _logger;

        public CategoryController(ILogger<CategoryController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            using var ctx = new PhotoContext();
            var categories = ctx.Categories.ToArray();

            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            using var ctx = new PhotoContext();

            if (!ModelState.IsValid)
            {
                return View(category);
            }

            ctx.Categories.Add(category);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            using var ctx = new PhotoContext();

            var cat = ctx.Categories.FirstOrDefault(c => c.Id == id);

            if (cat == null)
            {
                return NotFound();
            }

            return View(cat);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, Category category)
        {
            using var ctx = new PhotoContext();
            if (!ModelState.IsValid)
            {
                return View(category);
            }

            var catToUpdate = ctx.Categories.FirstOrDefault(c => c.Id == id);

            if (catToUpdate == null)
            {
                return NotFound();
            }

            catToUpdate.Name = category.Name;

            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            using var ctx = new PhotoContext();

            var catToDelete = ctx.Categories.FirstOrDefault(c => c.Id == id);

            if (catToDelete is null)
            {
                return View("NotFound");
            }

            ctx.Categories.Remove(catToDelete);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

net-il-mio-fotoalbum/Controllers/MessageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using net_il_mio_fotoalbum.Models;

namespace net_il_mio_fotoalbum.Controllers
{
    public class MessageController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            using var ctx = new PhotoContext();
            var messages = ctx.Messages.ToArray();
            return View(messages);
        }
        public IActionResult Send()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            using var ctx = new PhotoContext();

            var mesToDelete = ctx.Messages.FirstOrDefault(m => m.Id == id);

            if (mesToDelete is null)
            {
                return View("NotFound");
            }

            ctx.Messages.Remove(mesToDelete);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

net-il-mio-fotoalbum/Controllers/PhotoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using net_il_mio_fotoalbum.Models;
using System.Data;

namespace net_il_mio_fotoalbum.Controllers
{
    public class PhotoController : Controller
    {
        private readonly ILogger<PhotoController> _logger;

        public PhotoController(ILogger<PhotoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Portfolio()
        {
            return View();
        }

        public IActionResult Detail(int id)
        {
            using var ctx = new PhotoContext();
            var photo = ctx.Photos.Include(p => p.Categories).SingleOrDefault(p => p.Id == id);

            if (photo is null)
            {
                return NotFound($"Foto con id {id} non trovata.");
            }

            return View(photo);
        }

        [Authorize]
        public IActionResult Create()
        {
            using var ctx = new PhotoContext();
            var formModel = new PhotoFormModel
            {
                Categories = ctx.Categories.ToArray(),
            };

            return View(formModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PhotoFormModel form)
        {
            using var ctx = new PhotoContext();

            if (!ModelState.IsValid)
            {
                form.Categories = ctx.Categories.ToArray();

                return View(form);
            }

            form.Photo.Categories = ctx.Categories.Where(c => form.SelectedCategoriesIds.Contains(c.Id)).ToList();

            ctx.Photos.Add(form.Photo);
            ctx.SaveChanges();

            return RedirectToAction("Portfolio");
        }

        [Authorize]
        public IActionResult Update(int id)
        {
            using var ctx = new PhotoContext();

            var photo = ctx.Photos.Include(p => p.Categories).FirstOrDefault(p => p.Id == id);

            if (photo == null)
            {
                return NotFound();
            }

            var formModel = new PhotoFormModel
            {
                Photo = photo,  
                Categories = ctx.Categories.ToList(),
                SelectedCategoriesIds = photo.Categories!.Select(t => t.Id).ToList()
            };

            return View(formModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, PhotoFormModel form)
        {
            using var ctx = new PhotoContext();

            if (!ModelState.IsValid)
            {
                form.Categories = ctx.Categories.ToArray();

                return View(form);
            }

            var savedPhoto = ctx.Photos.Include(p => p.Categories).FirstOrDefault(p => p.Id == id);

            if (savedPhoto is null)
            {
                return View("NotFound");
            }

            savedPhoto.Title = form.Photo.Title;
            savedPhoto.Description = form.Photo.Description;
            savedPhoto.ImgSrc = form.Photo.ImgSrc;
            savedPhoto.Visible = form.Photo.Visible;
            savedPhoto.Categories = ctx.Categories.Where(t => form.SelectedCategoriesIds.Contains(t.Id)).ToList();

            ctx.SaveChanges();

            return RedirectToAction("Portfolio");
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            using var ctx = new PhotoContext();

            var photoToDelete = ctx.Photos.FirstOrDefault(p => p.Id == id);

            if (photoToDelete is null)
            {
                return View("NotFound");
            }

            ctx.Photos.Remove(photoToDelete);
            ctx.SaveChanges();

            return RedirectToAction("Portfolio");
        }

    }
}

net-il-mio-fotoalbum/Views/Shared/_Card.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@model Photo
@{
    var photo = Model;
}

<div class="personal-card">
    <a href="@Url.Action("Detail",new { Id = photo.Id})"><img src="@photo.ImgSrc" /></a>
    <div class="text-container">
        <h2>@photo.Title</h2>

        @if (SignInManager.IsSignedIn(User))
        {
            <div class="btn-container">
                <a href="@Url.Action("Update",new { Id = photo.Id})" class="personal-btn personal-btn-secondary">Modifica</a>
                <form asp-controller="Photo" asp-action="Delete" asp-route-id="@photo.Id" method="post">
                    @Html.AntiForgeryToken()
                    <button class="personal-btn personal-btn-secondary"> Elimina </button>
                </form>
            </div>
            @if (photo.Visible == true)
            {
                <p>Pubblico</p>
            }
            else
            {
                <p style="color:darkred">Privato</p>
            }
        }
    </div>
</div>

net-il-mio-fotoalbum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Album</title>
    <link rel="icon" type="image/x-icon" href="~/icon.png" />
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@    
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/net_il_mio_fotoalbum.styles.css" asp-append-version="true" />*@
</head>
<body>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

net-il-mio-fotoalbum/Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<nav>
    <a href="@Url.Action("Portfolio", "Photo")" class="title">Album</a>
    <div class="nav-function">
        @if (SignInManager.IsSignedIn(User))
        {
            <a class="single-function" href="@Url.Action("Create", "Photo")">Nuova Foto</a>
            <a class="single-function" href="@Url.Action("Index", "Category")">Categorie</a>
            <a class="single-function" href="@Url.Action("Index", "Message")">Messaggi</a>
            <form id="logoutForm" class="" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Photo", new { area = "" })">
                <button id="logout" type="submit" class="single-function">Logout</button>
            </form>
        }
        else
        {
            <a class="single-function" href="@Url.Action("Send", "Message")">Contatta</a>
            <a class="single-function" id="login" asp-area="Identity" asp-page="/Account/Login">Accedi</a>
        }
    </div>
</nav>